### ISSUE TITLE
Using Pusher JS

### ISSUE THREAD

**Issue by hrishiballal** [edgurgel/poxa#50] opened 2015-09-23 12:26 UTC
Hello, 
I have been looking at this a bit more and trying to use Pusher JS. 

A couple of issues, When I use the following to initialise the presence app, it gives me a app does not exist error: 
```javascript
  var pusher = new Pusher('presence-demo', {
  wsHost: 'poxa.herokuapp.com',
  wsPort: 80,
  enabledTransports: ["ws", "flash"],
  disabledTransports: ["flash"]
});
```
Pusher.com uses API keys, how can one use the APP_ID, APP_KEY and APP_SECRET using Pusher-js?

**Comment by edgurgel** [comment] 2015-09-26 06:13
Pusher has the concept of `app id`, `app key` and the `secret`. The client uses the `app key` to identify with the server. 

I just updated the README to make it clear: https://github.com/edgurgel/poxa/commit/577344b5d10ce4e2587b851fc99a5a7031306787

I would suggest reading the tutorials: https://pusher.com/tutorials

**Comment by hrishiballal** [comment] 2015-09-27 20:41
Thank you for your response, I am familiar with basics of Pusher since I am currently using it for a production app. 

A couple of things: 
When the app is deployed on Heroku, what is the port should a client connect to? Should wsPort be 8080 or 80? Heroku does not allow custom ports so hen I change [config.exs] (https://github.com/edgurgel/poxa/blob/master/config/config.exs) to port 80 (or 8080), connection is not established. Chrome says pending on network tab when using Pusherjs. When using hte presence example using Crypyo JS, the websocket.onopen event is triggered although the Network tab still says pending. The URL it is connecting to is below:

```
ws://poxa.herokuapp.com:8080/app/app_key?protocol=7&client=js&version=2.2.4&flash=false
ws://poxa.herokuapp.com/app/app_key?protocol=7&client=js&version=2.2.4&flash=false
```
When I use Pusher's Python library, and run the following to make a connection, I am Invalid app id for it. 

```python
import pusher
p = pusher.Pusher( app_id="app_id" , key="app_key", secret="secret", host="poxa.herokuapp.com" )
```

Thanks for your input, really appreciate your time and this library. Keep up the great job. Sample HTML to test is below.

```html
<!DOCTYPE html PUBLIC"-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
<TITLE>Poxa test</TITLE>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="//js.pusher.com/3.0/pusher.min.js"></script>
<script src="https://poxa.herokuapp.com/static/js/hmac-sha256.js"></script>

<script type = 'text/javascript'>
var pusher = new Pusher('app_key', {
  wsHost: 'poxa.herokuapp.com',
  wsPort: 8080,
  enabledTransports: ["ws", "flash"],
  disabledTransports: ["flash"]
});
function connect(appKey, secret) {
  var qs = authQS(appKey, secret);
  var host = 'poxa.herokuapp.com';
  websocket = new WebSocket(websocketProtocol() + "//" + host  + "/console?" + qs);
  websocket.onopen = function(evt) { onOpen(evt) };
  websocket.onclose = function(evt) { onClose(evt) };
  websocket.onmessage = function(evt) { onMessage(evt) };
  websocket.onerror = function(evt) { onError(evt) };
};

function authQS(appKey, secret) {
  var auth_key = appKey;
  var auth_timestamp = Math.round(new Date().getTime() / 1000);
  var params = { auth_key:auth_key,
                 auth_timestamp:auth_timestamp,
                 auth_version:"1.0" } ;
  var auth_signature = CryptoJS.HmacSHA256("GET\n/console\n" + $.param(params), secret).toString();
  return $.param($.extend({ }, params, { auth_signature:auth_signature }));
}

function disconnect() {
  websocket.close();
};

function isSecure() {
  return window.location.protocol == 'https:';
}

function websocketProtocol() {
  return isSecure() ? 'wss:' : 'ws:';
}
function onOpen(evt) {

  console.log("Websocket connected");
};

function onClose(evt) {
  console.log("Websocket closed");
};

function onMessage(evt) {
  incrementCounter();
  var data = JSON.parse(evt.data);
  addEvent(data.type, data.socket, data.details, data.time);
};

function onError(evt) {
  console.log("Error: " + evt);
};
function addEvent(type, socket, details, time) {
  var label = '<td class="' + labelClass(type) + '">' + type + '</td>';
  var row = label +
            '<td>' + socket + '</td>' +
            '<td>' + details + '</td>' +
            '<td>' + time + '</td>';
  $('#events > tbody:last').prepend('<tr>' + row + '</tr>');
};
function incrementCounter() {
  counter++;
  $('#counter').text(counter);
};
</script>
</HEAD>
<BODY>

  <table id="events" class="table table-striped table-hover">
        <thead>
          <tr>
            <th>Type</th>
            <th>Socket</th>
            <th>Details</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
</BODY>
</HTML>
```

**Comment by edgurgel** [comment] 2015-09-27 21:49
You can use ENV variables to configure Poxa on Heroku:

https://github.com/edgurgel/poxa/blob/master/config/config.exs#L9

```
PORT
POXA_APP_KEY
POXA_SECRET
POXA_APP_ID
```

This should probably be part of the Heroku section on the `README.md`.

I'm not sure why the Python library is failing. Maybe because it's trying to use HTTPS? 

If that's the case it's necessary to configure heroku to server through SSL as well. As far as I remember you can simply add an addon and use their wildcard certificate for *.herokuapp.com

Also I'm not sure why you are using the console page to connect to Poxa... The console is accessible through the root endpoint, example: `http://poxa.herokuapp.com/`

I always use this example to check if the heroku instance is working nicely: http://poxa-presence-chat.herokuapp.com/

It looks fine to me. Can you double check if the problem is the SSL port?

**Comment by hrishiballal** [comment] 2015-10-29 22:04
Hi Sorry for the delay in writing from my side. I have been testing this a bit more and here is what I have. 
In the config.exs file I have set the port to 443 (SSL) and deployed on Heroku (https://poxa-test.herokuapp.com/) 

You can see that using app_key and secret, it is connecting fine, but I cannot use it via the Javascript and Python libraries, I think that your hunch is correct. Unfortunately Heroku charges 20/month for SSL (!) and I need SSL for the app so I will not be using this, it is a pity.

**Comment by edgurgel** [comment] 2015-11-02 20:41
You can probably check if the client libraries accept not using SSL. Pusher JS has the option use unencrypted connections with Pusher/Poxa.

**Comment by edgurgel** [comment] 2015-11-02 20:42
It doesn't look like a real issue with Poxa and Pusher JS. I will be closing this issue and we can reopen if we find something new.

**Closed by edgurgel** 2015-11-02 20:42 UTC

**Comment by tkant** [comment] 2017-07-11 23:14
@hrishiballal @edgurgel Theres a regex inside Pusher libs where it checks for app_id to be an integer value. So you have to use integer value as app_id
